name: cm中转ip

permissions:
  contents: write   # 允许写入仓库（用于 git push）

on:
  schedule:
    - cron: '30 1 * * *'  # 每天 01:30 自动触发
  workflow_dispatch:      # 支持手动触发
  push:
    paths:
      - '**/ip.py'       # 当 Python 脚本更新时触发

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run ip.py to generate cm中转ip.txt
        working-directory: 中转
        run: python ip.py

      - name: Commit and push cm中转ip.txt if changed
        working-directory: 中转
        run: |
          if [ ! -f "cm中转ip.txt" ]; then
            echo "cm中转ip.txt not found, nothing to commit."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cm中转ip.txt

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update cm中转ip.txt (generated by GitHub Actions)"
            git push origin HEAD:main
          fi
